### ISSUE TITLE
Unable to use original type hint by defining relationship

### ISSUE THREAD

**Issue by Whitroom** [fastapi/sqlmodel#228]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

from sqlmodel import Field, SQLModel, Relationship, create_engine, Session

class Team(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    headquarters: str

    # key sentence
    heroes: list["Hero"] = Relationship(back_populates='team')

class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    secret_name: str
    age: Optional[int] = Field(default=None, index=True)

    team_id: Optional[int] = Field(default=None, foreign_key=Team.id)

database_url = f'mysql+mysqlconnector://{user}:{password}@{host}/{database_name}'

engine = create_engine(database_url, encoding='utf8', echo=True)

if __name__ == '__main__':
    SQLModel.metadata.create_all(engine)
```

### Description

I create Hero and Team models and try to use python original type hint, but while running it, it occurs exceptions...

Traceback (most recent call last):
  File "pydantic\validators.py", line 709, in pydantic.validators.find_validators
TypeError: issubclass() arg 1 must be a class

Traceback (most recent call last):
  File "C:\Users\10620\Desktop\Code\Python\sqlmodel\table_relationship.py", line 5, in <module>    
    class Team(SQLModel, table=True):
  File "C:\Users\10620\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlmodel\main.py", line 342, in __init__
    temp_field = ModelField.infer(
  File "pydantic\fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 728, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 778, in pydantic.fields.ModelField._create_sub_type
  File "pydantic\fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 539, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 801, in pydantic.fields.ModelField.populate_validators
  File "pydantic\validators.py", line 718, in find_validators
RuntimeError: error checking inheritance of 'Hero' (type: str)

The solution is adding List from typing and replacing it, but I don't know how to solve this bug...

link: https://sqlmodel.tiangolo.com/tutorial/relationship-attributes/define-relationships-attributes/

### Operating System

Windows

### SQLModel Version

0.0.6

### Python Version

3.10.1

**Comment by byrman** [comment]
I am not sure I understand your question correctly, but here `list["Hero"]` should indeed be `List["Hero"]`. From Python 3.9 onwards, generic `list[Hero]` should work as well, I think, but that requires your code to be rearranged, so that `Hero` is defined before `Team`.

**Comment by aleksul** [comment]
@Whitroom pls update to pydantic v1.9.1 - it should be fixed

**Comment by Shuntw6096** [comment]
I have meet a similar problem.
```python
class Base(SQLModel):
    pass

class Test:
    basemodel = Base
    __slots__ = 'filename', 'datamodel'
    def __init__(self, filename: str, datamodel: 'Base' = None, **kwargs):
        self.filename = filename
        if datamodel is not None:
            assert isinstance(datamodel, self.basemodel) # typehint: self.basemodel is Any, should be type[Base]
            self.datamodel = data_model
        else:
            self.datamodel = self.basemodel(**kwargs) # self.datamodel is Any, should be Base
```
if you remove the inheritance of Base, typehint work perfectly.
My stupid solution is add a classmethod to get the instance of Base.

```python
class Base(SQLModel):
    @classmethod
    def get_instance(cls, data: dict):
        return Base(**data)


class Test:
    basemodel = Base.get_instance
    __slots__ = 'filename', 'datamodel'
    def __init__(self, filename: str, datamodel: 'Base' = None, **kwargs):
        self.filename = filename
        if datamodel is not None:
            assert isinstance(datamodel, self.basemodel)
            self.datamodel = datamodel

        else:
            self.datamodel = self.basemodel(**kwargs)
```
Buy the way, filename is private attribute of Base at first, but idk how to init it.

**Comment by Shuntw6096** [comment]
I meet a similar problem,
```python
class Base(SQLModel):
    pass
class Test:
    basemodel = Base # type alias at here
    __slots__ = 'filename', 'datamodel'
    def __init__(self, filename: str, datamodel: Optional[Base] = None, **kwargs):
        self.filename = filename
        if datamodel is not None:
            assert isinstance(datamodel, self.basemodel) # self.basemodel is Any at here, should be type[Base]
            self.datamodel = datamodel
        else:
            self.datamodel = self.basemodel(**kwargs) # self.basemodel is Any at here, should be type[Base]
```
If you remove inheritance of Base, typehint work perfectly.
My stupid solution is adding a classmethod to get instance of Base,
```python
class Base(SQLModel, table=True):
    @classmethod
    def get_instance(cls, data: dict):
        return Base(**data)


class Test:
    basemodel = Base.get_instance
    __slots__ = 'filename', 'datamodel'
    def __init__(self, filename: str, datamodel: Optional[Base] = None, **kwargs):
        self.filename = filename
        if datamodel is not None:
            assert isinstance(datamodel, self.basemodel)
            self.datamodel = datamodel
        else:
            self.datamodel = self.basemodel(**kwargs)
```
Btw, filename is private attribute of Base, but idk how to init it.

**Comment by thribhu** [comment]
**Many to one relationship using sqlmodel and sqlalchemy along with alembic**
> When initializing mapper Mapper[Category(category)], expression \"relationship(\"Mapped[List['SubCategory']]\")\" seems to be using a generic class as the argument to relationship(); please state the generic argument using an annotation, e.g. \"subcategories: Mapped[Mapped[List['SubCategory']']] = relationship()\

I am facing an issue with many to one relationship. Having followed the [official documentation](https://sqlmodel.tiangolo.com/tutorial/relationship-attributes/define-relationships-attributes/), I created my relationship attributes inside my table. 
However, I receive an error from sqlalchemy like the above. My code is simple 

```py
from sqlmodel import SQLModel
from sqlmodel import Field
from sqlmodel import Relationship
from typing import Optional
from typing import List

class Category(SQLModel, table=True):
  id: int | None = Field(default=None, primary_key=True)
  name: str = Field(..., title="Category name")
  subcategories: List['SubCategory'] = Relationship(back_populates='category')
 
class SubCategory(SQLModel, table=True):
  id: int | None = Field(default=None, primary_key=True)
  name: str = Field(..., title="Sub category name")
  category_id: int | None = Field(default=None, foreign_key='category.id')
  category: 'Category' | None = Relationship(back_populates='subcategories')
```

**Comment by nicksonthc** [comment]
> **Many to one relationship using sqlmodel and sqlalchemy along with alembic**
> 
> > When initializing mapper Mapper[Category(category)], expression "relationship("Mapped[List['SubCategory']]")" seems to be using a generic class as the argument to relationship(); please state the generic argument using an annotation, e.g. "subcategories: Mapped[Mapped[List['SubCategory']']] = relationship()\
> 
> I am facing an issue with many to one relationship. Having followed the [official documentation](https://sqlmodel.tiangolo.com/tutorial/relationship-attributes/define-relationships-attributes/), I created my relationship attributes inside my table. However, I receive an error from sqlalchemy like the above. My code is simple
> 
> ```python
> from sqlmodel import SQLModel
> from sqlmodel import Field
> from sqlmodel import Relationship
> from typing import Optional
> from typing import List
> 
> class Category(SQLModel, table=True):
>   id: int | None = Field(default=None, primary_key=True)
>   name: str = Field(..., title="Category name")
>   subcategories: List['SubCategory'] = Relationship(back_populates='category')
>  
> class SubCategory(SQLModel, table=True):
>   id: int | None = Field(default=None, primary_key=True)
>   name: str = Field(..., title="Sub category name")
>   category_id: int | None = Field(default=None, foreign_key='category.id')
>   category: 'Category' | None = Relationship(back_populates='subcategories')
> ```


Same for me , i use tutorial Team and Hero class as sample code then get below error
```
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Team(team)]'. Original exception was: When initializing mapper Mapper[Team(team)], expression "relationship("List['Hero']")" seems to be using a generic class as the argument to relationship(); please state the generic argument using an annotation, e.g. "heroes: Mapped[List['Hero']] = relationship()"
```


Context
python 3.12.5
pydantic 2.9.2
sqlmodel 0.0.22

**Comment by nicksonthc** [comment]
Some update here, I tested with tutorial code with below sample and found out if import future annotations  might cause the mapper error, after remove the import then it's work.

```
class Team(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    headquarters: str

    heroes: list["Hero"] = Relationship(back_populates="team")


class Hero(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    secret_name: str
    age: int | None = Field(default=None, index=True)

    team_id: int | None = Field(default=None, foreign_key="team.id")
    team: Team | None = Relationship(back_populates="heroes")
```

## Import annotations might cause the mapper error
If in my model file got import annotations, then i will get the mappers error, after i remove `from __future__ import annotations` 
`from __future__ import annotations`

Error
![image](https://github.com/user-attachments/assets/189d801e-4f0e-4f4a-ab33-d363405e4b89)

Tutorial i refer to - https://sqlmodel.tiangolo.com/tutorial/relationship-attributes/define-relationships-attributes/#declare-relationship-attributes

## Context  & Environments
python 3.12
pydantic==2.9.2
SQLAlchemy==2.0.35
sqlmodel==0.0.22

**Comment by iloveitaly** [comment]
@nicksonthc I just ran into this same problem. Do you happen to know why that import causes this particular error?

**Comment by YuriiMotov** [comment]
The code from initial comment seems to work fine in current version (after changing `foreign_key=Team.id` to `foreign_key="team.id"`):

```py
from typing import Optional

from sqlmodel import Field, Relationship, SQLModel, create_engine

class Team(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    headquarters: str

    # key sentence
    heroes: list["Hero"] = Relationship(back_populates='team')

class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    secret_name: str
    age: Optional[int] = Field(default=None, index=True)

    team_id: Optional[int] = Field(default=None, foreign_key="team.id")  # Changed Team.id to "team.id"

database_url = 'sqlite:///'

engine = create_engine(database_url, echo=True)

if __name__ == '__main__':
    SQLModel.metadata.create_all(engine)
```

And, the [code example ](https://github.com/fastapi/sqlmodel/issues/228#issuecomment-2383321485)of @thribhu can be fixed by changing `'Category' | None` to `Union['Category',  None]`:

```py
from typing import List, Union

from sqlmodel import Field, Relationship, SQLModel

class Category(SQLModel, table=True):
  id: int | None = Field(default=None, primary_key=True)
  name: str = Field(..., title="Category name")
  subcategories: List['SubCategory'] = Relationship(back_populates='category')
 
class SubCategory(SQLModel, table=True):
  id: int | None = Field(default=None, primary_key=True)
  name: str = Field(..., title="Sub category name")
  category_id: int | None = Field(default=None, foreign_key='category.id')
  category: Union['Category',  None] = Relationship(back_populates='subcategories')
```

@Whitroom, could you please check it? Do you think we can close this issue now?
